### ISSUE TITLE
Relation to Feather Icons?

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [eucalyptuss/ucreate-icons#3]
I may be mistaken, buuut
as for me, the ikonate set looks way too close to [Feather icons](https://feathericons.com/). I even thought that ikonate is some kind of collab or an app for Feather icons at first glance.

Of course, they are separate packs, but I still wonder if Feather icons were used as a reference. The overall style and the icons that were chosen to be in the ikonate set make me question about it.

Btw I'm in no way affiliated to Feather icons, and those icons are distributed under the MIT license, too.

**Comment by eucalyptuss** [comment]
Hello
Thanks a lot for your feedback!

You're completely right that many of the icons in this set look similar to Feather, same as to many other icons sets. With the right set of settings, you can make some of them look almost identical if you want.  This is pretty much because both sets are based on SVG outlines and built on a similar grid. If you have 24 pixels square and want to keep your icons as simple and readable, it's rather inevitable that your plus icon will look similar to other plus icons in the world ;)

However, none of the icons here was copied from other source neither redrawn basing on some other icons set. There are some distinct differences that from my point of view make these icons a bit more universal / style-agnostic. Last, the main point of this script was to make svg icons customisation and sprite generation easier, not making just another icon set. If you want, you can even replace the icons with others and run the scripts on you own svg.
